[tools]
erlang = "29.1.1"
elixir = "1.20.4-otp-29"
node = "24.21.0"
pnpm = "12"

[env]
FUMEHOOD_DEV_PG16_URL = "postgres://postgres:fumehood@localhost:55416/fumehood_target"
FUMEHOOD_DEV_PG18_URL = "postgres://postgres:fumehood@localhost:55418/fumehood_target"
